# Generated by Django 5.1 on 2024-09-02 09:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userpage', '0002_auto_20240825_2104'),
    ]

    operations = [
        migrations.CreateModel(
            name='RestaurantInfo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description1', models.TextField(verbose_name='Paragraph 1')),
                ('description2', models.TextField(verbose_name='Paragraph 2')),
            ],
        ),
    ]
