# Generated by Django 5.1 on 2024-09-02 11:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('userpage', '0003_restaurantinfo'),
    ]

    operations = [
        migrations.DeleteModel(
            name='RestaurantInfo',
        ),
    ]
