# Generated by Django 5.1 on 2024-08-22 18:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('logsign', '0002_profile_email_profile_phone'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='email',
        ),
    ]
