# Generated by Django 5.1 on 2024-08-25 15:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('logsign', '0004_profile_full_name'),
    ]

    operations = [
    ]
