# Generated by Django 5.1 on 2024-08-25 15:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('adminpage', '0001_initial'),
    ]

    operations = [
    ]
