# Generated by Django 5.1 on 2024-08-30 07:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adminpage', '0002_auto_20240825_2104'),
    ]

    operations = [
        migrations.CreateModel(
            name='Add_Team',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=1000)),
                ('image', models.ImageField(upload_to='team/image')),
                ('designation', models.CharField(max_length=1000)),
            ],
        ),
        migrations.DeleteModel(
            name='CartItem',
        ),
    ]
