# Generated by Django 5.1 on 2024-08-24 18:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vrindavancard', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='generateimage',
            name='imag',
            field=models.ImageField(upload_to='qr_codes/'),
        ),
    ]
